server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  #    найти, где вызывается циркуляр
  main:
    allow-circular-references: true
  mvc:
    view:
      suffix: html
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
email:
  sender: kirpik.svyatoslav@yandex.ru
  password: wqmqochgwapzxpes