server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  main:
    allow-circular-references: true
  mvc:
    view:
      suffix: html
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true