CREATE TABLE workplaces (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR
);

INSERT INTO workplaces (name) VALUES ('load1');
INSERT INTO workplaces (name) VALUES ('load2');
INSERT INTO workplaces (name) VALUES ('tunnel');
INSERT INTO workplaces (name) VALUES ('clothespins1');
INSERT INTO workplaces (name) VALUES ('clothespins2');
INSERT INTO workplaces (name) VALUES ('booth1');
INSERT INTO workplaces (name) VALUES ('booth2');
INSERT INTO workplaces (name) VALUES ('unload1');
INSERT INTO workplaces (name) VALUES ('unload2');
INSERT INTO workplaces (name) VALUES ('pasting1');
INSERT INTO workplaces (name) VALUES ('pasting2');