create TABLE workplaces
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR,
    master_id INT
);

create TABLE workers
(
    id            INT PRIMARY KEY generated by default as identity,
    name          VARCHAR(255),
    profession    VARCHAR(255) NOT NULL,
    start_working DATE         NOT NULL,
    surname       varchar(255),
    workplace_id  INT,
    master_id     INT
);

create TABLE masters
(
    id      INT PRIMARY KEY generated by default as identity,
    name    VARCHAR(255),
    surname VARCHAR(255)
);


