CREATE TABLE workplaces (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR
);

INSERT INTO workplaces (name) VALUES ('load1');
INSERT INTO workplaces (name) VALUES ('load2');
INSERT INTO workplaces (name) VALUES ('tunnel');
INSERT INTO workplaces (name) VALUES ('clothespins1');
INSERT INTO workplaces (name) VALUES ('clothespins2');
INSERT INTO workplaces (name) VALUES ('booth1');
INSERT INTO workplaces (name) VALUES ('booth2');
INSERT INTO workplaces (name) VALUES ('unload1');
INSERT INTO workplaces (name) VALUES ('unload2');
INSERT INTO workplaces (name) VALUES ('pasting1');
INSERT INTO workplaces (name) VALUES ('pasting2');

CREATE TABLE workers (id INT PRIMARY KEY generated by default as identity,
                      name VARCHAR(255),
                      profession VARCHAR(255) NOT NULL,
                      start_working DATE NOT NULL,
                      surname varchar(255),
                      workplace_id INT,
                      master_id INT);

CREATE TABLE masters (id INT PRIMARY KEY generated by default as identity,
                      name VARCHAR(255),
                      surname VARCHAR(255));

INSERT INTO masters (name, surname) VALUES ('Sergey', 'Fedorinchik'),
                                            ('Andrey', 'Haritonchik'),
                                            ('Vitaliy', 'Kravchenko'),
                                            ('Alexandr', 'Belitskiy')